service: lyricsooc-bot
provider:
  name: aws
  runtime: nodejs14.x
functions:
  fetch:
    timeout: 20
    handler: handler.fetchTweets
    events:
      - schedule: rate(1 minute)
  postRandom:
    timeout: 20
    handler: handler.postRandom
    events:
      - schedule: rate(60 minutes)
